---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vk67220-pvc
  namespace: vk67220-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vk67220-storage
---
