---
apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.password }}
---
