---
apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: vk67220-ns
spec:
  serviceAccountName: emp-app-sa
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
---
