---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emp-app-role
  namespace: vk67220-ns
rules:
  - apiGroups: [""]
    resources: ["pods", "services","persistentvolumeclaims","configmaps","secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets","statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
---

