---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-svc
  namespace: vk67220-ns
spec:
  type: LoadBalancer
  selector:
    app: employee-app
  ports:
    - port: 80
      targetPort: 8080
---
