---
apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secrets
  namespace: vk67220-ns
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
---
